/**
 * Typed mock InfraProvider for unit tests.
 * Each repository method is a jest.fn() — callers can override with
 * mockResolvedValue / mockRejectedValue / mockImplementation as needed.
 */
import type { InfraProvider } from '@coploy/infra'

export function createMockInfra(): jest.Mocked<InfraProvider> {
	return {
		auth: {
			verifyToken: jest.fn(),
			createUser: jest.fn(),
			deleteUser: jest.fn(),
			getUserByEmail: jest.fn(),
			getUserByPhone: jest.fn(),
			createCustomToken: jest.fn(),
			signInWithPassword: jest.fn(),
			createUserAndGetToken: jest.fn(),
			// senha: gerar link de redefinição e trocar a senha do usuário
			updateUser: jest.fn(),
			generatePasswordResetLink: jest.fn(),
			setUserDisabled: jest.fn(),
			getUser: jest.fn(),
		},
		storage: {
			uploadFile: jest.fn(),
			getDownloadUrl: jest.fn(),
			downloadFile: jest.fn(),
			fileExists: jest.fn(),
			deleteFile: jest.fn(),
			deleteDirectory: jest.fn().mockResolvedValue({ deletedCount: 0 }),
			getPresignedUploadUrl: jest.fn(),
		},
		queue: {
			ensureQueueExists: jest.fn(),
			createTask: jest.fn(),
			getQueueInfo: jest.fn(),
			getFailedTasks: jest.fn(),
		},
		pubsub: {
			ensureTopicExists: jest.fn(),
			publish: jest.fn(),
			sendFailedTaskMessage: jest.fn(),
		},
		companyRepository: {
			getCompany: jest.fn(),
			listCompanies: jest.fn(),
			createCompany: jest.fn(),
			updateCompany: jest.fn(),
			getInsightsCache: jest.fn(),
			setInsightsCache: jest.fn(),
			listInsightsCache: jest.fn(),
			createInsightsCache: jest.fn(),
		},
		userRepository: {
			getUser: jest.fn(),
			updateUser: jest.fn(),
			createUser: jest.fn(),
			getUsersCompany: jest.fn(),
			createUsersCompany: jest.fn(),
			updateUsersCompany: jest.fn(),
			deleteUsersCompany: jest.fn(),
			getCandidateProfile: jest.fn(),
			createCandidateProfile: jest.fn(),
			updateCandidateProfile: jest.fn(),
			findUserByPhone: jest.fn(),
			findUserByEmail: jest.fn(),
			deleteUser: jest.fn(),
		},
		interviewHandoffRepository: {
			createHandoff: jest.fn(),
			consumeHandoff: jest.fn(),
		},
		otsAttestationRepository: {
			createAttestation: jest.fn(),
			getAttestation: jest.fn().mockResolvedValue(null),
			listAttestationsByUser: jest.fn().mockResolvedValue([]),
			revokeAttestation: jest.fn().mockResolvedValue(false),
		},
		taxonomyRepository: {
			listOccupations: jest.fn().mockResolvedValue([]),
			listSkills: jest.fn().mockResolvedValue([]),
			upsertOccupations: jest.fn().mockResolvedValue(0),
			upsertSkills: jest.fn().mockResolvedValue(0),
			recordPendingSkill: jest.fn(),
		},
		lgpdRepository: {
			listConsents: jest.fn().mockResolvedValue([]),
			createConsent: jest.fn().mockResolvedValue({ id: 'consent-1' }),
			revokeConsent: jest.fn(),
			listRequests: jest.fn().mockResolvedValue([]),
			createRequest: jest.fn().mockResolvedValue({ id: 'req-1' }),
			completeRequest: jest.fn(),
		},
		pessoaRepository: {
			getById: jest.fn(),
			findByCpf: jest.fn(),
			findByTarget: jest.fn(),
			create: jest.fn(),
			linkUser: jest.fn(),
			linkUsersCompany: jest.fn(),
			linkCandidateProfile: jest.fn(),
			listLinks: jest.fn(),
		},
		outboxRepository: {
			insert: jest.fn(),
			listPending: jest.fn(),
			claimPending: jest.fn(),
			markPublished: jest.fn(),
			markFailed: jest.fn(),
		},
		jobRepository: {
			getJob: jest.fn(),
			listJobs: jest.fn(),
			listPublicJobs: jest.fn(),
			listPublicJobsByCompany: jest.fn(),
			createJob: jest.fn(),
			updateJob: jest.fn(),
			syncPostJobUsersApplied: jest.fn(),
			getInfoJobByPostJob: jest.fn(),
			deleteJob: jest.fn(),
			listInfoJobs: jest.fn(),
			getInfoJob: jest.fn(),
			createInfoJob: jest.fn(),
			updateInfoJob: jest.fn(),
			deleteInfoJob: jest.fn(),
			getJobPortal: jest.fn(),
			// resolve null por default: é o fallback de branding — a maioria dos
			// testes não configura portal e não deve precisar saber que ele existe
			getJobPortalByCompany: jest.fn().mockResolvedValue(null),
			createJobPortal: jest.fn(),
			updateJobPortal: jest.fn(),
			createInterviewWhatsapp: jest.fn(),
		},
		candidateRepository: {
			getJobApplied: jest.fn(),
			// lista vazia é o que um repositório devolve; `undefined` não existe
			listJobsApplied: jest.fn().mockResolvedValue([]),
			createJobApplied: jest.fn(),
			updateJobApplied: jest.fn(),
			setJobApplied: jest.fn(),
			listCompanyInterviews: jest.fn(),
			listJobInterviews: jest.fn(),
			listPublicInterviews: jest.fn(),
			getPublicInterview: jest.fn(),
			listCandidateLikes: jest.fn(),
			createCandidateLike: jest.fn(),
			deleteCandidateLike: jest.fn(),
			getJobInterview: jest.fn(),
			setJobInterview: jest.fn(),
			updateJobInterview: jest.fn(),
			setCompanyInterview: jest.fn(),
			updateCompanyInterview: jest.fn(),
			listCompanyInterviewsForBackfill: jest.fn(),
			listAllCompanyInterviews: jest.fn(),
			getCompanyInterview: jest.fn(),
			countCompanyInterviews: jest.fn(),
			listAdminCandidateSummaries: jest.fn(),
			getAdminCandidateSummary: jest.fn(),
			findAdminCandidateSummariesByExact: jest.fn(),
			searchAdminCandidateSummariesByKeyword: jest.fn(),
			countAdminCandidateSummaries: jest.fn(),
			syncAdminCandidateSummaryInterview: jest.fn(),
			upsertPublicInterview: jest.fn(),
			updatePublicInterview: jest.fn(),
			deleteJobApplied: jest.fn(),
			deleteJobInterview: jest.fn(),
			deleteCompanyInterview: jest.fn(),
			updateJobAppliedInTransaction: jest.fn(),
		},
		collaboratorRepository: {
			getCollaborator: jest.fn(),
			listCollaborators: jest.fn(),
			createCollaborator: jest.fn(),
			updateCollaborator: jest.fn(),
			deleteCollaborator: jest.fn(),
		},
		notificationRepository: {
			listCompanyNotifications: jest.fn(),
			getCompanyNotification: jest.fn(),
			createCompanyNotification: jest.fn(),
			updateCompanyNotification: jest.fn(),
			deleteCompanyNotification: jest.fn(),
			listNotificationMessages: jest.fn(),
			getNotificationMessage: jest.fn(),
			createNotificationMessage: jest.fn(),
			updateNotificationMessage: jest.fn(),
			deleteNotificationMessage: jest.fn(),
		},
		/*
		 * Faltava aqui, e a falta escondia um defeito: `recordEvent` engole erro
		 * de propósito (histórico não pode derrubar a movimentação), então sem o
		 * repositório no mock o teste passava sem nunca provar que o evento é
		 * gravado.
		 */
		candidateTimelineRepository: {
			listTimeline: jest.fn().mockResolvedValue([]),
			appendEntry: jest.fn().mockResolvedValue({ id: 'tl-1' }),
			updateEntry: jest.fn().mockResolvedValue(undefined),
			deleteEntry: jest.fn().mockResolvedValue(undefined),
		},
		npsRepository: {
			listNps: jest.fn(),
			createNps: jest.fn(),
		},
		billingRepository: {
			listCreditsUsed: jest.fn(),
			getCreditsUsed: jest.fn(),
			createCreditsUsed: jest.fn(),
			listSubscriptionHistory: jest.fn(),
			createSubscriptionHistory: jest.fn(),
			createStripeWebhookHistory: jest.fn(),
			createBillingHistory: jest.fn(),
			listBillingHistory: jest.fn(),
		},
		batchRepository: {
			getBatch: jest.fn(),
			listBatches: jest.fn(),
			createBatch: jest.fn(),
			updateBatch: jest.fn(),
		},
		shortLinkRepository: {
			getShortLink: jest.fn(),
			createShortLink: jest.fn(),
		},
		hmReviewTokenRepository: {
			createReviewToken: jest.fn(),
			consumeReviewToken: jest.fn(),
			getByAccessCode: jest.fn(),
		},
		sharedCandidateLinkRepository: {
			create: jest.fn(),
			getByCode: jest.fn(),
		},
		conversationRepository: {
			getConversationContext: jest.fn(),
			listConversationContexts: jest.fn(),
			createConversationContext: jest.fn(),
			updateConversationContext: jest.fn(),
			deleteConversationContext: jest.fn(),
		},
		gupyIntegrationRepository: {
			getGupyIntegration: jest.fn(),
			listGupyIntegrations: jest.fn(),
			createGupyIntegration: jest.fn(),
			updateGupyIntegration: jest.fn(),
		},
		interviewAbandonmentRepository: {
			create: jest.fn(),
			list: jest.fn(),
		},
		rejectionReviewRequestRepository: {
			create: jest.fn(),
			findByJobAppliedId: jest.fn(),
			listPendingByCompany: jest.fn(),
			getById: jest.fn(),
			update: jest.fn(),
		},
		resultWebhookRepository: {
			listByCompany: jest.fn(),
			getById: jest.fn(),
			create: jest.fn(),
			update: jest.fn(),
			delete: jest.fn(),
		},
		webhookDeliveryLogRepository: {
			listByCompany: jest.fn(),
			listByWebhook: jest.fn(),
			getById: jest.fn(),
			create: jest.fn(),
		},
		auditLogRepository: {
			create: jest.fn(),
			list: jest.fn(),
		},
		aiUsageRepository: {
			create: jest.fn(),
			list: jest.fn(),
		},
		enterpriseContractRepository: {
			list: jest.fn(),
			getById: jest.fn(),
			listByCompany: jest.fn(),
			create: jest.fn(),
			update: jest.fn(),
			delete: jest.fn(),
		},
		enterprisePaymentRepository: {
			list: jest.fn(),
			listByCompany: jest.fn(),
			getById: jest.fn(),
			create: jest.fn(),
			update: jest.fn(),
			delete: jest.fn(),
		},
		talentCreditsRepository: {
			listCatalog: jest.fn(),
			getCatalogByCode: jest.fn(),
			upsertCatalogItem: jest.fn(),
			seedCatalog: jest.fn(),
			getWallet: jest.fn(),
			getOrCreateWallet: jest.fn(),
			listLedger: jest.fn(),
			getReservation: jest.fn(),
			findReservationByIdempotencyKey: jest.fn(),
			listExpiredReservations: jest.fn(),
			grant: jest.fn(),
			reserve: jest.fn(),
			capture: jest.fn(),
			release: jest.fn(),
			expire: jest.fn(),
		},
		globalSettingsRepository: {
			get: jest.fn().mockResolvedValue({}),
			update: jest.fn(),
		},
		motorLicenseRepository: {
			getByKeyHash: jest.fn(),
			list: jest.fn(),
			touch: jest.fn(),
		},
	} as unknown as jest.Mocked<InfraProvider>
}
