import { z } from 'zod'

export const JobStatus = {
	ALL: 'all',
	ACTIVE: 'active',
	INACTIVE: 'inactive',
} as const

export const JobInterviewType = {
	ALL: 'all',
	EVALUATION: 'evaluation',
	INTERVIEW: 'interview',
	EMOTIONAL: 'emotional',
	EXITJOB: 'exitJob',
} as const

export const JobLanguage = {
	ALL: 'all',
	PT: 'pt',
	EN: 'en',
	ES: 'es',
	FR: 'fr',
	IT: 'it',
} as const

/**
 * As categorias que o FILTRO de vaga aceita.
 *
 * Precisa cobrir tudo que o formulário oferece: o filtro é igualdade exata
 * sobre `jobCategories`, então categoria que o formulário grava e o enum não
 * conhece vira 400 na busca — e a vaga fica invisível para qualquer filtro por
 * área. A lista é a união do que a v1 oferece, do que o v2 oferecia e do que já
 * estava aqui (nenhuma entrada antiga saiu: vaga já cadastrada com ela
 * continuaria filtrável).
 */
export const JobCategories = {
	ALL: 'all',
	ADMINISTRATIVO: 'Administrativo',
	AGRICULTURA: 'Agricultura',
	AGRICULTURA_E_AGRONEGOCIOS: 'Agricultura e Agronegócios',
	AGRONEGOCIO: 'Agronegócio',
	ALIMENTACAO_RESTAURANTES_BARES: 'Alimentação (restaurantes, bares)',
	ALIMENTACAO_E_BEBIDAS: 'Alimentação e Bebidas',
	ALIMENTOS_E_BEBIDAS: 'Alimentos e Bebidas',
	ATENDIMENTO_AO_CLIENTE: 'Atendimento ao Cliente',
	AUDITORIA_CONTABIL_FISCAL_OU_FINANCEIRA: 'Auditoria contábil, fiscal ou financeira',
	AUTOMOTIVO_E_FABRICACAO: 'Automotivo e Fabricação',
	AUTOMOTIVO_E_MANUFATURA: 'Automotivo e Manufatura',
	BEM_ESTAR_E_FITNESS: 'Bem-estar e Fitness',
	BEM_ESTAR_E_FITNESS_2: 'Bem-Estar e Fitness',
	BENS_E_CONSUMO: 'Bens e Consumo',
	CIBERSEGURANCA: 'Cibersegurança',
	CIENCIA_E_PESQUISA: 'Ciência e Pesquisa',
	COMERCIAL_VENDAS: 'Comercial / Vendas',
	COMERCIO_ATACADISTA: 'Comércio atacadista',
	COMERCIO_VAREJISTA: 'Comércio varejista',
	COMUNICACAO_MARKETING: 'Comunicação / Marketing',
	CONSTRUCAO_CIVIL: 'Construção civil',
	CONSTRUCAO_CIVIL_2: 'Construção Civil',
	CONSTRUCAO_E_ENGENHARIA_CIVIL: 'Construção e Engenharia Civil',
	CONSULTORIA_E_ASSESSORAMENTO: 'Consultoria e Assessoramento',
	CONSULTORIA_E_ASSESSORIA: 'Consultoria e Assessoria',
	CUIDADO_PESSOAL_SALOES_SPAS: 'Cuidado Pessoal (salões, spas)',
	CULTURA_E_ARTE: 'Cultura e Arte',
	DADOS_BI: 'Dados / BI',
	DESIGN_CRIACAO: 'Design / Criação',
	EDUCACAO: 'Educação',
	EDUCACAO_ESCOLAS_UNIVERSIDADES_CURSOS: 'Educação (escolas, universidades, cursos)',
	EDUCACAO_E_ENSINO: 'Educação e Ensino',
	EDUCACAO_SUPERIOR_E_PESQUISA_CIENTIFICA: 'Educação Superior e Pesquisa Científica',
	ENERGIA_E_SUSTENTABILIDADE: 'Energia e Sustentabilidade',
	ENGENHARIA: 'Engenharia',
	FINANCAS_E_CONTABILIDADE: 'Finanças e Contabilidade',
	FINANCEIRO_CONTABIL: 'Financeiro / Contábil',
	IMOBILIARIO: 'Imobiliário',
	INDUSTRIA_AUTOMOTIVA: 'Indústria Automotiva',
	INDUSTRIA_DE_ALIMENTOS_E_BEBIDAS: 'Indústria de Alimentos e Bebidas',
	INDUSTRIA_DE_ELETRONICOS: 'Indústria de Eletrônicos',
	INDUSTRIA_DE_MOVEIS: 'Indústria de Móveis',
	INDUSTRIA_METALURGICA: 'Indústria Metalúrgica',
	INDUSTRIA_QUIMICA_E_PETROQUIMICA: 'Indústria Química e Petroquímica',
	INDUSTRIA_TEXTIL: 'Indústria Têxtil',
	JURIDICO: 'Jurídico',
	LIMPEZA_E_CONSERVACAO: 'Limpeza e Conservação',
	LOGISTICA_TRANSPORTE: 'Logística / Transporte',
	MANUTENCAO: 'Manutenção',
	MARKETING_E_PUBLICIDADE: 'Marketing e Publicidade',
	MIDIA_E_ENTRETENIMENTO: 'Mídia e Entretenimento',
	MINERACAO: 'Mineração',
	MODA_E_DESIGN: 'Moda e Design',
	ONGS_E_ASSOCIACOES: 'ONGs e Associações',
	ORGANIZACOES_GOVERNAMENTAIS: 'Organizações Governamentais',
	PRODUCAO_OPERACOES: 'Produção / Operações',
	PRODUTO: 'Produto',
	PUBLICIDADE_E_MARKETING: 'Publicidade e Marketing',
	RECURSOS_HUMANOS: 'Recursos Humanos',
	SAUDE: 'Saúde',
	SAUDE_HOSPITAIS_CLINICAS_LABORATORIOS: 'Saúde (hospitais, clínicas, laboratórios)',
	SAUDE_E_CUIDADOS_MEDICOS: 'Saúde e Cuidados Médicos',
	SEGURANCA_DO_TRABALHO: 'Segurança do Trabalho',
	SEGURANCA_PATRIMONIAL: 'Segurança Patrimonial',
	SERVICOS_CONTABEIS: 'Serviços Contábeis',
	SERVICOS_DE_DESIGN_E_INOVACAO: 'Serviços de Design e Inovação',
	SERVICOS_DE_VIGILANCIA_E_SEGURANCA_PATRIMONIAL: 'Serviços de Vigilância e Segurança Patrimonial',
	SERVICOS_FINANCEIROS_BANCOS_CORRETORAS: 'Serviços Financeiros (bancos, corretoras)',
	SERVICOS_GERAIS: 'Serviços Gerais',
	SERVICOS_GOVERNAMENTAIS: 'Serviços Governamentais',
	SERVICOS_JURIDICOS: 'Serviços Jurídicos',
	SERVICOS_JURIDICOS_EXTENDIDOS: 'Serviços Jurídicos Extendidos',
	SILVICULTURA_FLORESTAS: 'Silvicultura (florestas)',
	TECNOLOGIA_DA_INFORMACAO: 'Tecnologia da Informação',
	TELECOMUNICACOES: 'Telecomunicações',
	TRANSPORTE_E_LOGISTICA: 'Transporte e Logística',
	TURISMO_E_HOSPITALIDADE: 'Turismo e Hospitalidade',
	TURISMO_E_HOTELARIA: 'Turismo e Hotelaria',
	VENDAS_E_ATENDIMENTO_AO_CLIENTE: 'Vendas e Atendimento ao Cliente',
} as const

export const JobCareerLevel = {
	ALL: 'all',
	ESTAGIARIO: 'Estagiário',
	TRAINEE: 'Trainee',
	JUNIOR: 'Júnior',
	ASSISTENTE: 'Assistente',
	OPERACIONAL: 'Operacional',
	ASSOCIADO: 'Associado',
	TECNICO: 'Técnico',
	ANALISTA: 'Analista',
	PLENO: 'Pleno',
	SENIOR: 'Sênior',
	ESPECIALISTA: 'Especialista',
	CONSULTOR_SENIOR: 'Consultor Sênior',
	COORDENADOR: 'Coordenador',
	GERENTE: 'Gerente',
	GERENTE_PROJETO: 'Gerente de Projeto',
	CHEFE: 'Chefe',
	DIRETOR: 'Diretor',
	DIRETOR_OPERACOES: 'Diretor de Operações (COO)',
	DIRETOR_FINANCEIRO: 'Diretor Financeiro (CFO)',
	CTO: 'Chief Technology Officer (CTO)',
	CMO: 'Chief Marketing Officer (CMO)',
	CEO: 'Diretor Executivo (CEO)',
	NAO_INFORMADO: 'Não Informado',
} as const

export const JobEducationLevel = {
	ALL: 'all',
	ENSINO_MEDIO: 'Ensino Médio',
	ENSINO_SUPERIOR_CURSANDO: 'Ensino Superior (Cursando)',
	ENSINO_SUPERIOR: 'Ensino Superior',
	POS_GRADUACAO: 'Pós Graduação',
	MESTRADO: 'Mestrado',
	DOUTORADO: 'Doutorado',
	TECNICO: 'Técnico',
} as const

// Schemas Zod para validação
export const jobStatusEnum = z.enum([
	JobStatus.ALL,
	JobStatus.ACTIVE,
	JobStatus.INACTIVE,
])

export const jobInterviewTypeEnum = z.enum([
	JobInterviewType.ALL,
	JobInterviewType.EVALUATION,
	JobInterviewType.INTERVIEW,
	JobInterviewType.EMOTIONAL,
	JobInterviewType.EXITJOB,
])

export const jobLanguageEnum = z.enum([
	JobLanguage.ALL,
	JobLanguage.PT,
	JobLanguage.EN,
	JobLanguage.ES,
	JobLanguage.FR,
	JobLanguage.IT,
])

export const jobCategoriesEnum = z.enum([
	JobCategories.ALL,
	JobCategories.ADMINISTRATIVO,
	JobCategories.AGRICULTURA,
	JobCategories.AGRICULTURA_E_AGRONEGOCIOS,
	JobCategories.AGRONEGOCIO,
	JobCategories.ALIMENTACAO_RESTAURANTES_BARES,
	JobCategories.ALIMENTACAO_E_BEBIDAS,
	JobCategories.ALIMENTOS_E_BEBIDAS,
	JobCategories.ATENDIMENTO_AO_CLIENTE,
	JobCategories.AUDITORIA_CONTABIL_FISCAL_OU_FINANCEIRA,
	JobCategories.AUTOMOTIVO_E_FABRICACAO,
	JobCategories.AUTOMOTIVO_E_MANUFATURA,
	JobCategories.BEM_ESTAR_E_FITNESS,
	JobCategories.BEM_ESTAR_E_FITNESS_2,
	JobCategories.BENS_E_CONSUMO,
	JobCategories.CIBERSEGURANCA,
	JobCategories.CIENCIA_E_PESQUISA,
	JobCategories.COMERCIAL_VENDAS,
	JobCategories.COMERCIO_ATACADISTA,
	JobCategories.COMERCIO_VAREJISTA,
	JobCategories.COMUNICACAO_MARKETING,
	JobCategories.CONSTRUCAO_CIVIL,
	JobCategories.CONSTRUCAO_CIVIL_2,
	JobCategories.CONSTRUCAO_E_ENGENHARIA_CIVIL,
	JobCategories.CONSULTORIA_E_ASSESSORAMENTO,
	JobCategories.CONSULTORIA_E_ASSESSORIA,
	JobCategories.CUIDADO_PESSOAL_SALOES_SPAS,
	JobCategories.CULTURA_E_ARTE,
	JobCategories.DADOS_BI,
	JobCategories.DESIGN_CRIACAO,
	JobCategories.EDUCACAO,
	JobCategories.EDUCACAO_ESCOLAS_UNIVERSIDADES_CURSOS,
	JobCategories.EDUCACAO_E_ENSINO,
	JobCategories.EDUCACAO_SUPERIOR_E_PESQUISA_CIENTIFICA,
	JobCategories.ENERGIA_E_SUSTENTABILIDADE,
	JobCategories.ENGENHARIA,
	JobCategories.FINANCAS_E_CONTABILIDADE,
	JobCategories.FINANCEIRO_CONTABIL,
	JobCategories.IMOBILIARIO,
	JobCategories.INDUSTRIA_AUTOMOTIVA,
	JobCategories.INDUSTRIA_DE_ALIMENTOS_E_BEBIDAS,
	JobCategories.INDUSTRIA_DE_ELETRONICOS,
	JobCategories.INDUSTRIA_DE_MOVEIS,
	JobCategories.INDUSTRIA_METALURGICA,
	JobCategories.INDUSTRIA_QUIMICA_E_PETROQUIMICA,
	JobCategories.INDUSTRIA_TEXTIL,
	JobCategories.JURIDICO,
	JobCategories.LIMPEZA_E_CONSERVACAO,
	JobCategories.LOGISTICA_TRANSPORTE,
	JobCategories.MANUTENCAO,
	JobCategories.MARKETING_E_PUBLICIDADE,
	JobCategories.MIDIA_E_ENTRETENIMENTO,
	JobCategories.MINERACAO,
	JobCategories.MODA_E_DESIGN,
	JobCategories.ONGS_E_ASSOCIACOES,
	JobCategories.ORGANIZACOES_GOVERNAMENTAIS,
	JobCategories.PRODUCAO_OPERACOES,
	JobCategories.PRODUTO,
	JobCategories.PUBLICIDADE_E_MARKETING,
	JobCategories.RECURSOS_HUMANOS,
	JobCategories.SAUDE,
	JobCategories.SAUDE_HOSPITAIS_CLINICAS_LABORATORIOS,
	JobCategories.SAUDE_E_CUIDADOS_MEDICOS,
	JobCategories.SEGURANCA_DO_TRABALHO,
	JobCategories.SEGURANCA_PATRIMONIAL,
	JobCategories.SERVICOS_CONTABEIS,
	JobCategories.SERVICOS_DE_DESIGN_E_INOVACAO,
	JobCategories.SERVICOS_DE_VIGILANCIA_E_SEGURANCA_PATRIMONIAL,
	JobCategories.SERVICOS_FINANCEIROS_BANCOS_CORRETORAS,
	JobCategories.SERVICOS_GERAIS,
	JobCategories.SERVICOS_GOVERNAMENTAIS,
	JobCategories.SERVICOS_JURIDICOS,
	JobCategories.SERVICOS_JURIDICOS_EXTENDIDOS,
	JobCategories.SILVICULTURA_FLORESTAS,
	JobCategories.TECNOLOGIA_DA_INFORMACAO,
	JobCategories.TELECOMUNICACOES,
	JobCategories.TRANSPORTE_E_LOGISTICA,
	JobCategories.TURISMO_E_HOSPITALIDADE,
	JobCategories.TURISMO_E_HOTELARIA,
	JobCategories.VENDAS_E_ATENDIMENTO_AO_CLIENTE,
])

export const jobCareerLevelEnum = z.enum([
	JobCareerLevel.ALL,
	JobCareerLevel.ESTAGIARIO,
	JobCareerLevel.TRAINEE,
	JobCareerLevel.JUNIOR,
	JobCareerLevel.ASSISTENTE,
	JobCareerLevel.OPERACIONAL,
	JobCareerLevel.ASSOCIADO,
	JobCareerLevel.TECNICO,
	JobCareerLevel.ANALISTA,
	JobCareerLevel.PLENO,
	JobCareerLevel.SENIOR,
	JobCareerLevel.ESPECIALISTA,
	JobCareerLevel.CONSULTOR_SENIOR,
	JobCareerLevel.COORDENADOR,
	JobCareerLevel.GERENTE,
	JobCareerLevel.GERENTE_PROJETO,
	JobCareerLevel.CHEFE,
	JobCareerLevel.DIRETOR,
	JobCareerLevel.DIRETOR_OPERACOES,
	JobCareerLevel.DIRETOR_FINANCEIRO,
	JobCareerLevel.CTO,
	JobCareerLevel.CMO,
	JobCareerLevel.CEO,
	JobCareerLevel.NAO_INFORMADO,
])

export const jobEducationLevelEnum = z.enum([
	JobEducationLevel.ALL,
	JobEducationLevel.ENSINO_MEDIO,
	JobEducationLevel.ENSINO_SUPERIOR_CURSANDO,
	JobEducationLevel.ENSINO_SUPERIOR,
	JobEducationLevel.POS_GRADUACAO,
	JobEducationLevel.MESTRADO,
	JobEducationLevel.DOUTORADO,
	JobEducationLevel.TECNICO,
])

export type JobStatusType = (typeof JobStatus)[keyof typeof JobStatus]
export type JobInterviewTypeType =
	(typeof JobInterviewType)[keyof typeof JobInterviewType]
export type JobLanguageType = (typeof JobLanguage)[keyof typeof JobLanguage]
export type JobCategoriesType =
	(typeof JobCategories)[keyof typeof JobCategories]
export type JobCareerLevelType =
	(typeof JobCareerLevel)[keyof typeof JobCareerLevel]
export type JobEducationLevelType =
	(typeof JobEducationLevel)[keyof typeof JobEducationLevel]
